In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
folder_path = "C:/Users/qhrrl/CodeExamples/3.Paper/0.Dataset"

In [4]:
pd_cur_train = pd.read_csv(folder_path + '/cur_training_all.csv')
pd_vib_train = pd.read_csv(folder_path + '/vib_training_all.csv')
pd_cur_val = pd.read_csv(folder_path + '/cur_validation_all.csv')
pd_vib_val = pd.read_csv(folder_path + '/vib_validation_all.csv')

In [6]:
print(len(pd_cur_train))
print(len(pd_cur_val))
print("=" * 50)
print(len(pd_vib_train))
print(len(pd_vib_val))

305534
38210
196032
24522


In [7]:
pd_cur_train.head(3)

Date  R_AbsMax  S_AbsMax  T_AbsMax  R_AbsMean  S_AbsMean  \
0  2020-11-13 07:43:41  3.643555  3.883789  4.124023   2.152260   2.154582   
1  2020-11-13 07:43:41  3.643555  3.803711  4.164062   2.161249   2.163811   
2  2020-11-13 07:43:41  3.683594  3.803711  4.164062   2.152920   2.151939   

   T_AbsMean     R_P2P     S_P2P     T_P2P  ...      S_2x      T_2x      R_3x  \
0   2.290735  7.126953  7.527344  7.687500  ...  3.553066  3.763136  0.021705   
1   2.301946  7.126953  7.447266  7.727539  ...  3.533756  3.747315  0.009876   
2   2.289333  7.166992  7.367188  7.727539  ...  3.519853  3.728701  0.017622   

       S_3x      T_3x      R_4x      S_4x      T_4x  WATT  LABEL  
0  0.023957  0.020911  0.057528  0.057195  0.057517   2.2      0  
1  0.010175  0.010687  0.011616  0.013211  0.010941   2.2      0  
2  0.011568  0.014016  0.012954  0.016530  0.011328   2.2      0  

[3 rows x 48 columns]

In [8]:
pd_vib_train.head(3)

Date    AbsMax   AbsMean       P2P       RMS  Skewness  \
0  2020-11-25 15:47:09  0.031503  0.002348  0.041003  0.002963 -0.252712   
1  2020-11-25 15:47:12  0.050405  0.002355  0.061181  0.003016 -0.658560   
2  2020-11-25 15:47:15  0.026258  0.002471  0.036879  0.003133 -0.281960   

    Kurtosis      Crest     Shape    Impulse        1x        2x        3x  \
0   4.821787  13.839364  1.261929  13.418192  0.000168  0.000179  0.000778   
1  11.017264  20.288108  1.280328  21.400306  0.000550  0.000262  0.000381   
2   4.263064  11.769368  1.268231  10.627622  0.000262  0.000239  0.000797   

         4x       1xB       2xB       3xB       4xB  WATT  LABEL  
0  0.000514  0.000215  0.000408  0.000186  0.001045   2.2      0  
1  0.000484  0.000168  0.000309  0.000311  0.001069   2.2      0  
2  0.000665  0.000154  0.000403  0.000160  0.001294   2.2      0

In [9]:
np_cur_train = pd_cur_train.to_numpy()
np_cur_val = pd_cur_val.to_numpy()

np_vib_train = pd_vib_train.to_numpy()
np_vib_val = pd_vib_val.to_numpy()

# Extract Labels

In [10]:
cur_train_labels = np_cur_train[:,-1]
cur_val_labels = np_cur_val[:, -1]

vib_train_labels = np_vib_train[:,-1]
vib_val_labels = np_vib_val[:, -1]

print(cur_train_labels)
print(cur_val_labels)
print(vib_train_labels)
print(vib_val_labels)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [12]:
np.mean(vib_val_labels)

1.1105537884348748

In [13]:
pd_cur_train = pd_cur_train.drop(columns = ['Date','WATT','LABEL'])
pd_cur_val = pd_cur_val.drop(columns = ['Date','WATT','LABEL'])

pd_vib_train = pd_vib_train.drop(columns = ['Date','WATT','LABEL'])
pd_vib_val = pd_vib_val.drop(columns = ['Date','WATT','LABEL'])

# 딥러닝 용 데이터로 전처리

In [14]:
pd_cur_train.head(3)

R_AbsMax  S_AbsMax  T_AbsMax  R_AbsMean  S_AbsMean  T_AbsMean     R_P2P  \
0  3.643555  3.883789  4.124023   2.152260   2.154582   2.290735  7.126953   
1  3.643555  3.803711  4.164062   2.161249   2.163811   2.301946  7.126953   
2  3.683594  3.803711  4.164062   2.152920   2.151939   2.289333  7.166992   

      S_P2P     T_P2P     R_RMS  ...      T_1x      R_2x      S_2x      T_2x  \
0  7.527344  7.687500  2.393055  ...  0.003780  3.536451  3.553066  3.763136   
1  7.447266  7.727539  2.405001  ...  0.012369  3.521399  3.533756  3.747315   
2  7.367188  7.727539  2.394561  ...  0.012448  3.506221  3.519853  3.728701   

       R_3x      S_3x      T_3x      R_4x      S_4x      T_4x  
0  0.021705  0.023957  0.020911  0.057528  0.057195  0.057517  
1  0.009876  0.010175  0.010687  0.011616  0.013211  0.010941  
2  0.017622  0.011568  0.014016  0.012954  0.016530  0.011328  

[3 rows x 45 columns]

In [15]:
pd_vib_train.head(3)

AbsMax   AbsMean       P2P       RMS  Skewness   Kurtosis      Crest  \
0  0.031503  0.002348  0.041003  0.002963 -0.252712   4.821787  13.839364   
1  0.050405  0.002355  0.061181  0.003016 -0.658560  11.017264  20.288108   
2  0.026258  0.002471  0.036879  0.003133 -0.281960   4.263064  11.769368   

      Shape    Impulse        1x        2x        3x        4x       1xB  \
0  1.261929  13.418192  0.000168  0.000179  0.000778  0.000514  0.000215   
1  1.280328  21.400306  0.000550  0.000262  0.000381  0.000484  0.000168   
2  1.268231  10.627622  0.000262  0.000239  0.000797  0.000665  0.000154   

        2xB       3xB       4xB  
0  0.000408  0.000186  0.001045  
1  0.000309  0.000311  0.001069  
2  0.000403  0.000160  0.001294

In [16]:
cur_train = pd_cur_train.to_numpy()
cur_val = pd_cur_val.to_numpy()

vib_train = pd_vib_train.to_numpy()
vib_val = pd_vib_val.to_numpy()

# 1. Current

## 1.1 Data

### 1.1 split data set 

In [210]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(cur_train, cur_train_labels, stratify=cur_train_labels, test_size=0.2, random_state=42)

### 1.2. Validation

In [211]:
print(x_train.shape)
print(x_test.shape)

print("="*50)

print(y_train.shape)
print(y_test.shape)

print("="*50)

x_valid = cur_val
y_valid = vib_val_labels

print(x_valid.shape)
print(y_valid.shape)

(244427, 45)
(61107, 45)
(244427,)
(61107,)
(38210, 45)
(24522,)


### 1.3 normalize

In [212]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

# Standard Scaler를 적용하고 싶을 경우 아래 Code를 실행

stder = StandardScaler()
stder.fit(x_train)

x_train = stder.transform(x_train)
x_valid = stder.transform(x_valid)

# Robust Scaler를 적용하고 싶을 경우 아래 주석을 해제하고 Code를 실행

# rscaler = RobustScaler() 
# rscaler.fit(x_train)
# x_train = rscaler.transform(x_train)
# x_valid = rscaler.transform(x_valid)

주제가 피쳐에 대한 강건함이므로, 스케일러에 대한 고민도 해야할 것이다.

본 데이터는 Multivariate이며, 1개의 Channel만 갖는다. 우리는 multivariate variable with one channel 형태로 바꿔주고자 하며, 이는 아래와 같다.

In [213]:
# CNN, RNN 모델의 입력 변수는 채널 축 1개 차원을 확장시킨 3D Tensor이다.
# 즉 아래 CNN, RNN 모델은 x_train, x_valid, x_test를 입력 변수로 넣지 않고, 
# x_train_exp, x_valid_exp, x_test_exp을 넣는다. 
x_train_exp = np.expand_dims(x_train, -1)  # 채널 축 1개 차원을 확장 시킨(Expand) X_train
x_valid_exp = np.expand_dims(x_valid, -1)  # 채널 축 1개 차원을 확장 시킨(Expand) X_vaild 
x_test_exp = np.expand_dims(x_test, -1)  # 채널 축 1개 차원을 확장 시킨(Expand) X_test

# 위와 동일한 코드
# x_train_exp = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
# x_valid_exp = x_train.reshape((x_valid.shape[0], x_valid.shape[1], 1))
# x_test_exp = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

print("x_train_exp의 형태:", x_train_exp.shape)
print("x_valid_exp의 형태:", x_valid_exp.shape)
print("x_test_exp의 형태:", x_test_exp.shape)

x_train_exp의 형태: (244427, 45, 1)
x_valid_exp의 형태: (38210, 45, 1)
x_test_exp의 형태: (61107, 45, 1)


In [214]:
type(y_train)

numpy.ndarray

In [215]:
# y_train = y_train.astype('int')
# y_valid = y_valid.astype('int')
# y_test = y_test.astype('int')

y_train = tf.stack(y_train)
y_valid = tf.stack(y_valid)
y_test = tf.stack(y_test)

In [217]:
print(y_train)
print(y_valid)
print(y_test)

tf.Tensor([0 0 0 ... 3 2 0], shape=(244427,), dtype=int32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(24522,), dtype=int32)
tf.Tensor([0 0 0 ... 0 2 2], shape=(61107,), dtype=int32)


In [218]:
num_classes = len(np.unique(np.concatenate((y_train, y_test), axis=0)))
num_classes

5

In [219]:
x_train_exp.shape

(244427, 45, 1)

In [220]:
y_train.shape

TensorShape([244427])

# 3. LSTM

In [221]:
import h5py

from tensorflow.keras.callbacks import Callback, EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Flatten, Dense

def make_lstm_model():
    model = Sequential()
    model.add(LSTM(units=256, return_sequences=True))
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(5, activation='softmax'))
    return model

In [222]:
lstm = make_lstm_model()

In [223]:
lstm.build(x_train_exp.shape)

In [224]:
lstm.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_13 (LSTM)               (244427, 45, 256)         264192    
_________________________________________________________________
flatten_13 (Flatten)         (244427, 11520)           0         
_________________________________________________________________
dense_26 (Dense)             (244427, 100)             1152100   
_________________________________________________________________
dense_27 (Dense)             (244427, 5)               505       
Total params: 1,416,797
Trainable params: 1,416,797
Non-trainable params: 0
_________________________________________________________________


In [225]:
EPOCHS = 100
BATCH_SIZE = 64

In [226]:
lstm.compile(loss="sparse_categorical_crossentropy", 
                  optimizer='adam', 
                  metrics=["accuracy"]
                 )

In [227]:
callbacks = [ModelCheckpoint('lstm_best_model.h5', 
                             monitor='val_loss',
                             save_best_only=True),
             ReduceLROnPlateau(
                 monitor="val_loss", factor=0.5, patience=20, min_lr=0.0001
                 ),
             EarlyStopping(monitor="val_loss", patience=10, verbose=1)
             ]

In [228]:
df = tf.stack(y_train)
y_train = tf.stack(df)

In [229]:
y_train

<tf.Tensor: shape=(244427,), dtype=int32, numpy=array([0, 0, 0, ..., 3, 2, 0])>

In [230]:
history = lstm.fit(
    x_train_exp,
    y_train,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    callbacks=callbacks,
    validation_data=(x_valid_exp, y_valid),
    verbose=1
)

Epoch 1/100
3819/3820 [============================>.] - ETA: 0s - loss: 0.1143 - accuracy: 0.9574

ValueError: Data cardinality is ambiguous:
  x sizes: 38210
  y sizes: 24522
Make sure all arrays contain the same number of samples.

In [ ]:
lstm = history
scores = lstm.evaluate(x_test_exp, y_test)

print("\n""Test accuracy", scores[1])
print("\n""Test loss", scores[0])
print("%s: %.2f%%" % (rnn_model.metrics_names[1], scores[1]*100))

In [ ]:
draw_confusion_matrix(lstm, x_test_exp, y_test, "lstm")

In [ ]:
draw_roc(lstm, x_test_exp, y_test, "lstm")

In [ ]:
plot_loss_graph(lstm, "lstm")

In [ ]:
plot_prediction_graph(lstm, "lstm")